"""table candidate profile

Revision ID: 215a5f56c07c
Revises: 65295303b68c
Create Date: 2024-10-01 21:33:47.663759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215a5f56c07c'
down_revision = '65295303b68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_code', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tps_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tps_no')

    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
