"""table candidate profile add image

Revision ID: 527fe02e365a
Revises: 215a5f56c07c
Create Date: 2024-10-01 22:19:21.508588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527fe02e365a'
down_revision = '215a5f56c07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
