"""add client_code to appsettings

Revision ID: 61a9f9bc6c6f
Revises: f4e03557a766
Create Date: 2024-09-30 12:39:20.630512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a9f9bc6c6f'
down_revision = 'f4e03557a766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_code', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'clients', ['client_code'], ['client_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_code')

    # ### end Alembic commands ###
