"""add is_verified

Revision ID: 65295303b68c
Revises: a7de83fdbdfc
Create Date: 2024-10-01 16:33:06.109083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65295303b68c'
down_revision = 'a7de83fdbdfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pemilih', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pemilih', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
