"""add fernet key

Revision ID: 737cd93d53cb
Revises: 40282ef2e72f
Create Date: 2024-09-28 17:29:24.817686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737cd93d53cb'
down_revision = '40282ef2e72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fernet_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fernet_key')

    # ### end Alembic commands ###
