"""add client_code to modelused

Revision ID: 8f7b2a4adc62
Revises: 61a9f9bc6c6f
Create Date: 2024-09-30 12:48:02.449961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7b2a4adc62'
down_revision = '61a9f9bc6c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_used', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_code', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'clients', ['client_code'], ['client_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_used', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_code')

    # ### end Alembic commands ###
