"""remove fk village_code

Revision ID: a7de83fdbdfc
Revises: 662514e201a2
Create Date: 2024-10-01 13:03:54.079817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7de83fdbdfc'
down_revision = '662514e201a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pemilih', schema=None) as batch_op:
        batch_op.alter_column('village_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint('data_pemilih_village_code_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pemilih', schema=None) as batch_op:
        batch_op.create_foreign_key('data_pemilih_village_code_fkey', 'villages', ['village_code'], ['code'])
        batch_op.alter_column('village_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
