"""update nik length (to store encrypted nik)

Revision ID: ad0ce2e0e852
Revises: 737cd93d53cb
Create Date: 2024-09-28 17:59:36.021883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0ce2e0e852'
down_revision = '737cd93d53cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pemilih', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pemilih', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
