"""add dpts table

Revision ID: aff04ab0cb4d
Revises: 8f7b2a4adc62
Create Date: 2024-10-01 10:18:15.871317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff04ab0cb4d'
down_revision = '8f7b2a4adc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dpts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=False),
    sa.Column('city_code', sa.String(length=5), nullable=False),
    sa.Column('subdistrict_code', sa.String(length=8), nullable=False),
    sa.Column('ward_code', sa.String(length=13), nullable=True),
    sa.Column('village_code', sa.String(length=255), nullable=True),
    sa.Column('tps_no', sa.String(length=20), nullable=True),
    sa.Column('nik', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('rt', sa.String(length=10), nullable=True),
    sa.Column('rw', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['city_code'], ['cities.code'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['subdistricts.code'], ),
    sa.ForeignKeyConstraint(['village_code'], ['villages.code'], ),
    sa.ForeignKeyConstraint(['ward_code'], ['wards.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dpts')
    # ### end Alembic commands ###
