from app import db

class DataPemilih(db.Model):
    __tablename__ = 'data_pemilih'
    id = db.Column(db.Integer, primary_key=True)
    client_code = db.Column(db.String(255), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    model_id = db.Column(db.Integer, db.ForeignKey('models.id'), nullable=False)
    province_id = db.Column(db.Integer, db.ForeignKey('provinces.id'), nullable=False)
    regency_id = db.Column(db.Integer, db.ForeignKey('regencies.id'), nullable=False)
    subdistrict_id = db.Column(db.Integer, db.ForeignKey('subdistricts.id'), nullable=False)
    urban_villages_id = db.Column(db.Integer, db.ForeignKey('urban_villages.id'), nullable=False)
    village_id = db.Column(db.Integer, db.ForeignKey('villages.id'), nullable=False)
    s3_file = db.Column(db.String(255), nullable=False)
    nik = db.Column(db.String(255), unique=True, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    birth_date = db.Column(db.Date, nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    address = db.Column(db.Text, nullable=False)
    no_phone = db.Column(db.String(20))
    no_tps = db.Column(db.String(20))
    is_party_member = db.Column(db.Boolean, default=False)
    relation_to_candidate = db.Column(db.String(50))
    confirmation_status = db.Column(db.String(20))
    category = db.Column(db.String(20))
    positioning_to_candidate = db.Column(db.String(50))
    expectation_to_candidate = db.Column(db.Text)
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    updated_at = db.Column(db.DateTime, server_default=db.func.now(), server_onupdate=db.func.now())